:concurrency: 3
:timeout: 60
:verbose: false
:queues:
  - critical
  - default
  - mailers
  - active_storage_analysis
  - active_storage_purge

:scheduler:
  mark_cart_as_abandoned_job:
    cron: "0 */3 * * *" # every 3 hours
    class: "MarkCartAsAbandonedJob"
    queue: default

  remove_cart_abandoned_job:
    cron: "0 0 * * 0" # every Sunday at midnight
    class: "RemoveCartAbandonedJob"
    queue: default